package mod.iceandshadow3.compat;

import java.util.List;

import mod.iceandshadow3.basics.BlockLogic;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.ItemStack;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextComponentString;
import net.minecraft.world.IBlockAccess;
import net.minecraftforge.common.IShearable;

public class ABlock extends Block implements BlockLogic.IProvider, IShearable {
	protected final BlockLogic bl;
	public ABlock(BlockLogic blocklogic) {
		super(blocklogic.getMateria().mcmat);
		bl = blocklogic;
		this.blockHardness = bl.getMateria().getBaseHardness();
		this.blockResistance = bl.getMateria().getBaseBlastResist();
		this.lightOpacity = bl.getMateria().getBaseOpacity();
		this.lightValue = bl.getMateria().getBaseLuma();
		this.translucent = ! bl.getMateria().isOpaque();
	}
	
	@Override
	public BlockLogic getBlockLogic() {
		return bl;
	}

	@Override
	public boolean isShearable(ItemStack item, IBlockAccess world, BlockPos pos) {
		return bl.getMateria().isToolClassEffective(HarvestMethod.SHEAR);
	}

	@Override
	public List<ItemStack> onSheared(ItemStack item, IBlockAccess world, BlockPos pos, int fortune) {
		//TODO: Autogenerated methodist stub.
		return null;
	}
}
