name: CI
on:
  pull_request: {}
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./gradlew classes
    - name: Test+Check
      run: ./gradlew check
